config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'events', to: 'events#index'

  get 'events/:code', to: 'events#show', :as => 'event'

  get 'projects', to: 'events#projects', :as => 'events_projects'

  get 'events/:code/:project_name', to: 'project#index', :as => 'project'


  namespace :admin do
    root to: 'events#index'

    resources :users do
      member do
        get 'edit_password', to: 'users#edit_password'
        get 'equipes', to: 'users#equipes'
        patch 'user_password', to: 'users#update_password'
        put 'user_password', to: 'users#update_password'
      end
    end


    get 'home_configuration', to: 'home_configuration#index'

    patch 'home_configuration', to: 'home_configuration#update'
    put 'home_configuration', to: 'home_configuration#update'

    resources :events, param: :code do
      member do
        get 'event_subscribe', to: 'events#event_subscribe'

        resources :event_users, :path => 'users', except:[:show, :edit, :update] do
          collection do
            get 'new_manager', to: 'event_users#new_manager'
            post 'create_manager', to: 'event_users#create_manager'
          end
        end

        resources :teams, as: :event_teams do
          resources :team_users, :path => 'members', :as => 'users', except:[:index, :show]
          resources :projects, except:[:index, :show]
        end
      end
    end
  end

  devise_for :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_users, dependent: :destroy
  has_many :users, :through => :event_users
  has_many :teams, dependent: :destroy
  has_many :projects, through: :teams

  has_one :image, :as => :imageable, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  validates :name, :date, :address, :description, presence: true


  accepts_nested_attributes_for :image, :reject_if => :all_blank

  def create_image
    default_image = self.build_image
    File.open('./public/projects/bg1.jpg') do |f|
      default_image.image = f
    end
  end

  def self.events_markers
    events = Event.all

    markers = ""

    events.each do |event|
      markers+="&markers=#{event.latitude}%2C#{event.longitude}"
    end
    markers
  end

  def to_param
    "#{code}".parameterize
  end

  def is_the_user? user, role
    !self.event_users.where(user_id: user, role: EventUser.roles[role]).empty?
  end

  def there_is_the_user? user
    self.is_the_user? user, :organizador or
    self.is_the_user? user, :medhacker
  end


  def self.create_code
    if Event.all.empty?
      number = sprintf '%05d', 1
    else
      number = sprintf '%05d', (Event.last.code[3..7].to_i + 1)
    end

    "MH-" + number
  end

  def only_one_organizer?
    self.event_users.where(role: EventUser.roles[:organizador]).count == 1
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [:event_subscribe, :show, :edit, :update, :destroy]
  add_breadcrumb "Eventos", :admin_events_path

  # GET /events
  # GET /events.json
  def index
    #@events = Event.all
    @events = policy_scope(Event.paginate(:page => params[:page], :per_page => 9).order('created_at DESC'))
    authorize @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    add_breadcrumb "#{@event.code}", :admin_event_path
    authorize @event
  end

  # GET /events/new
  def new
    add_breadcrumb "Novo Evento", :new_admin_event_path
    @event = Event.new(code: Event.create_code)
    authorize @event

    @event.build_image
  end

  # GET /events/1/edit
  def edit
    authorize @event

    add_breadcrumb "#{@event.code}", :admin_event_path
    add_breadcrumb "Edit Evento", :edit_admin_event_path
    if @event.image.nil?
      @event.build_image
    end
  end

  def event_subscribe
    authorize @event

    @event.event_users.build(user: current_user, role: EventUser.roles[:medhacker])

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Inscrição realizada com sucesso.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html {
          flash[:Error] = "Você já está inscrito no evento."
          redirect_to admin_event_path(:code => @event.code) }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new()
    authorize @event

    @event = Event.new(permitted_attributes(@event))

    @event.code = Event.create_code
    @event.code.upcase!

    if @event.image.nil?
      @event.create_image
    end

    user = @event.event_users.build
    user.user = current_user
    user.role = 1

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Evento foi CRIADO com sucesso.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html { render :new }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event

    respond_to do |format|
      if @event.update(permitted_attributes(@event))
        @event.code.upcase!
        format.html { redirect_to [:admin, @event], notice: 'Evento foi ATUALIZADO com sucesso.' }
        format.json { render :show, status: :ok, location: [:admin, @event] }
      else
        format.html { render :edit }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event

    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Evento foi EXCLUÍDO com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(code: params[:code].upcase)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :address, :description,
        :release_sign_up, :published, image_attributes: [:image])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def index
    @events = Event.where(published: true).paginate(:page => params[:page], :per_page => 6)
      .order('created_at DESC')
  end

  def show
#    @projects = Project.all(:team).where(event_id: @event)
    @projects = @event.projects
  end

  def projects
    @projects = Project.joins(team: :event).where(events: {published: true})
      .paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
  end

  private
  def set_event
    @event = Event.find_by(code: params[:code].upcase)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_form.html.erb
<%= simple_form_for([:admin, @event]) do |f| %>
  <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :code, label: "Código",  disabled: true%>
    </div>

    <div class="form-inputs">
      <%= f.input :name, label: "Nome"%>
    </div>

    <div class="form-inputs">
      <%= f.label :date, label: "Data" %>
      <%= date_field(:event, :date) %>
    </div>

    <div class="form-inputs">
      <%= f.input :address, label: "Endereço" %>
    </div>

    <div class="form-inputs">
      <%= f.input :description, label: "Descrição" %>
    </div>

    <%= f.simple_fields_for :image do |i| %>
      <div class="form-inputs">
        <%= i.input :image, as: :image_preview, input_html: {preview_version: :slider_thumb}, label: "< 1200 x 480 >"%>
      </div>
    <% end %>

    <div class="form-inputs">
      <%= f.input :release_sign_up, label: "Liberar Inscrições" %>
    </div>

    <div class="form-inputs">
      <%= f.input :published, label: "Publicar" %>
    </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Enviar", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/admin/events/edit.html.erb
<div class="container">
  <div class="row centered">
      <h2> Editar Evento </h2>
      <hr>
   </div>

  <div class="row col-lg-10 col-lg-offset-1">
    <%= render 'form' %>
  </div>
</div>

<div class="container">
  <br>
  <div class="well row centered ">
    <!-- Single button -->
    <div class="btn-group">
      <button type="button" class="btn btn-danger  btn-sm  dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Excluir <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Excluir do Sistema', [:admin, @event], method: :delete, data: { confirm: 'Tem certeza?' } %></li>
      </ul>
    </div>

  </div>
</div>

app/views/admin/events/index.html.erb
<div class="container">
  <% if policy(Event).create? %>
  <div class="row centered">
      <h2> <%= link_to new_admin_event_path, class: "btn btn-primary" do %>
        <i class="fa fa-plus-circle"></i> Novo Evento
      <% end %>
      </h2>
      <hr>
  </div>
  <% end %>


<div class="row col-lg-8 col-lg-offset-2">

<div class="panel panel-info">
  <!-- Default panel contents -->
  <div class="panel-heading"><b>Eventos</b></div>

<table class="table table-hover table-responsive", style="background:#fff">
  <thead>
    <tr>
      <th>Código</th>
      <th>Nome</th>
      <th>Data</th>
      <th>Inscrição liberada</th>
      <th>Publicado</th>
      <th>Inscrito</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.code %></td>

        <td><%= event.name %></td>
        <td><%= event.date %></td>
        <td>
          <% if event.release_sign_up %>
            <i class="fa fa-check" style="color: green"></i>
          <% else %>
            <i class="fa fa-times" style="color: red"></i>
          <% end %>
        </td>
        <td>
          <% if event.published %>
            <i class="fa fa-check" style="color: green"></i>
          <% else %>
            <i class="fa fa-times" style="color: red"></i>
          <% end %>
        </td>

        <td>
          <% if event.there_is_the_user? current_user %>
            <i class="fa fa-circle"></i>
          <% else %>
            <i class="fa fa-circle-thin"></i>
          <% end %>
        </td>

        <td>
          <%= link_to admin_event_path(event) do %>
            <i class="fa fa-eye btn btn-default btn-xs"></i>
          <% end %>
        </td>

        <% if policy(event).create? %>
        <td>
          <%= link_to edit_admin_event_path(event) do %>
            <i class="fa fa-pencil btn btn-default btn-xs"></i>
          <% end %>
        </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

</div>
</div>

<div class="container">
<div class="row">
  <div class="text-center"> <%= will_paginate @events, renderer: BootstrapPagination::Rails, previous_label: "Voltar", next_label: "Próxima"  %> </div>
</div>
</div>

app/views/admin/events/new.html.erb
<div class="container">
  <div class="row centered">
      <h2> Novo Evento </h2>
      <hr>
   </div>

<div class="row col-lg-10 col-lg-offset-1">
<%= render 'form' %>
</div>

</div>

app/views/admin/events/show.html.erb
<div class="container">
  <div class="row centered">
      <h2> <%= @event.code %> - <b><%= @event.name %></b> </h2>
      <hr>
    </div><!-- /row mt -->

      <!-- edit form column -->
<div class="col-lg-10 col-lg-offset-1 centered">

    <% if !@event.image.nil? %>
      <%= image_tag @event.image.image.slider.url, height: "200", class:"img-thumbnail" %>
    <% else %>
      <%= image_tag 'bg3.jpg', height: "200", class:"img-thumbnail" %>
    <% end %>
</div>


<div class="col-lg-5 col-lg-offset-1">
  <h4>Detalhes do Evento</h4>
  <p><%= @event.description %></p>
  <p><b>Publicado:</b>
        <% if @event.published %>
          <i class="fa fa-check" style="color: green"></i>
        <% else %>
          <i class="fa fa-times" style="color: red"></i>
        <% end %>
  </p>
  <p><b>Inscrições liberadas:</b>
        <% if @event.release_sign_up %>
          <i class="fa fa-check" style="color: green"></i>
        <% else %>
          <i class="fa fa-times" style="color: red"></i>
        <% end %>
  </p>
  <br>
  <% if @event.release_sign_up %>
    <% if @event.there_is_the_user? current_user %>
      <div class="text-center">
        <button type="button" class="btn btn-default btn-lg btn-block" disabled="disabled"> Inscrito </button>
      </div>
    <% else %>
      <div class="text-center">
        <%= link_to 'Inscreva-se', event_subscribe_admin_event_path,  class: "btn btn-success btn-lg btn-block" %>
      </div>
    <% end %>
  <%end%>
  <br>
</div>

<div class="col-lg-4 col-lg-offset-1">
  <h4>Informações do Evento</h4>
  <p><b>Data:</b> <%= @event.date %></p>
  <p><b>Local:</b> <%= @event.address %></p>

  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}",  height: "200" %>
</div>

</div>

<div class="event_show container">
    <div class="row well centered">

      <% if policy(@event).edit? %>
      <%= link_to 'Editar', edit_admin_event_path(@event) , class: "btn btn-primary" %> &nbsp;
      <% end %>


      <%= link_to 'Usuários do Evento', admin_event_users_path, class: "btn btn-info" %>  &nbsp;


      <%= link_to 'Equipes', admin_event_teams_path, class: "btn btn-warning" %>
    </div>
</div>