config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'events', to: 'events#index'

  get 'events/:code', to: 'events#show', :as => 'event'

  get 'projects', to: 'events#projects', :as => 'events_projects'

  get 'events/:code/:project_name', to: 'project#index', :as => 'project'


  namespace :admin do
    root to: 'events#index'

    resources :users do
      member do
        get 'edit_password', to: 'users#edit_password'
        get 'equipes', to: 'users#equipes'
        patch 'user_password', to: 'users#update_password'
        put 'user_password', to: 'users#update_password'
      end
    end


    get 'home_configuration', to: 'home_configuration#index'

    patch 'home_configuration', to: 'home_configuration#update'
    put 'home_configuration', to: 'home_configuration#update'

    resources :events, param: :code do
      member do
        get 'event_subscribe', to: 'events#event_subscribe'

        resources :event_users, :path => 'users', except:[:show, :edit, :update] do
          collection do
            get 'new_manager', to: 'event_users#new_manager'
            post 'create_manager', to: 'event_users#create_manager'
          end
        end

        resources :teams, as: :event_teams do
          resources :team_users, :path => 'members', :as => 'users', except:[:index, :show]
          resources :projects, except:[:index, :show]
        end
      end
    end
  end

  devise_for :users
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :event_users, dependent: :destroy
  has_many :users, :through => :event_users
  has_many :teams, dependent: :destroy
  has_many :projects, through: :teams

  has_one :image, :as => :imageable, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, :if => lambda{ |obj| obj.address_changed? }

  validates :name, :date, :address, :description, presence: true


  accepts_nested_attributes_for :image, :reject_if => :all_blank

  def create_image
    default_image = self.build_image
    File.open('./public/projects/bg1.jpg') do |f|
      default_image.image = f
    end
  end

  def self.events_markers
    events = Event.all

    markers = ""

    events.each do |event|
      markers+="&markers=#{event.latitude}%2C#{event.longitude}"
    end
    markers
  end

  def to_param
    "#{code}".parameterize
  end

  def is_the_user? user, role
    !self.event_users.where(user_id: user, role: EventUser.roles[role]).empty?
  end

  def there_is_the_user? user
    self.is_the_user? user, :organizador or
    self.is_the_user? user, :medhacker
  end


  def self.create_code
    if Event.all.empty?
      number = sprintf '%05d', 1
    else
      number = sprintf '%05d', (Event.last.code[3..7].to_i + 1)
    end

    "MH-" + number
  end

  def only_one_organizer?
    self.event_users.where(role: EventUser.roles[:organizador]).count == 1
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::AdminController
  before_action :set_event, only: [:event_subscribe, :show, :edit, :update, :destroy]
  add_breadcrumb "Eventos", :admin_events_path

  # GET /events
  # GET /events.json
  def index
    #@events = Event.all
    @events = policy_scope(Event.paginate(:page => params[:page], :per_page => 9).order('created_at DESC'))
    authorize @events
  end

  # GET /events/1
  # GET /events/1.json
  def show
    add_breadcrumb "#{@event.code}", :admin_event_path
    authorize @event
  end

  # GET /events/new
  def new
    add_breadcrumb "Novo Evento", :new_admin_event_path
    @event = Event.new(code: Event.create_code)
    authorize @event

    @event.build_image
  end

  # GET /events/1/edit
  def edit
    authorize @event

    add_breadcrumb "#{@event.code}", :admin_event_path
    add_breadcrumb "Edit Evento", :edit_admin_event_path
    if @event.image.nil?
      @event.build_image
    end
  end

  def event_subscribe
    authorize @event

    @event.event_users.build(user: current_user, role: EventUser.roles[:medhacker])

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Inscrição realizada com sucesso.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html {
          flash[:Error] = "Você já está inscrito no evento."
          redirect_to admin_event_path(:code => @event.code) }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new()
    authorize @event

    @event = Event.new(permitted_attributes(@event))

    @event.code = Event.create_code
    @event.code.upcase!

    if @event.image.nil?
      @event.create_image
    end

    user = @event.event_users.build
    user.user = current_user
    user.role = 1

    respond_to do |format|
      if @event.save
        format.html { redirect_to [:admin, @event], notice: 'Evento foi CRIADO com sucesso.' }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html { render :new }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    authorize @event

    respond_to do |format|
      if @event.update(permitted_attributes(@event))
        @event.code.upcase!
        format.html { redirect_to [:admin, @event], notice: 'Evento foi ATUALIZADO com sucesso.' }
        format.json { render :show, status: :ok, location: [:admin, @event] }
      else
        format.html { render :edit }
        format.json { render json: [:admin, @event].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    authorize @event

    @event.destroy
    respond_to do |format|
      format.html { redirect_to admin_events_url, notice: 'Evento foi EXCLUÍDO com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(code: params[:code].upcase)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date, :address, :description,
        :release_sign_up, :published, image_attributes: [:image])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show]

  def index
    @events = Event.where(published: true).paginate(:page => params[:page], :per_page => 6)
      .order('created_at DESC')
  end

  def show
#    @projects = Project.all(:team).where(event_id: @event)
    @projects = @event.projects
  end

  def projects
    @projects = Project.joins(team: :event).where(events: {published: true})
      .paginate(:page => params[:page], :per_page => 6).order('created_at DESC')
  end

  private
  def set_event
    @event = Event.find_by(code: params[:code].upcase)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="container">
<div class="row text-center">
   <br>
   <h2> Eventos MedHacker</h2>
   <hr>
</div>


<section>
    <div class="container">
    <div class="row">
        <ul class="grid cs-style-3">
    <% @events.each do |event| %>
        <li>
            <figure>
                <%= image_tag event.image.image.project.url , class: "img-responsive" %>
                <figcaption>
                    <h3><%= event.name%></h3>
                    
                        <span></span>

                        <%= link_to "Ver Evento", event_path(code: event.code)%>
                </figcaption>
            </figure>
        </li>
    <%end%>
        </ul>
    </div>
    </div>
</section><!--/#portfolio-item-->

</div>

<div class="container">
<div class="row">
  <div class="text-center"> <%= will_paginate @events, renderer: BootstrapPagination::Rails, previous_label: "Voltar", next_label: "Próxima" %> </div>
</div>
</div>

</div>

app/views/events/projects.html.erb
<div class="container">

<div class="row text-center">
   <br>
   <h2> Projetos MedHacker</h2>
   <hr>
</div>

<section id="portfolio">
       <div class="row">

        <% @projects.each do |project| %>
                <div class="portfolio-items">
                    <div class="portfolio-item apps col-xs-12 col-sm-4 col-md-4">
                        <div class="recent-work-wrap">

                           <%= image_tag project.images[1].image.project.url , class: "img-responsive" %>

                            <div class="overlay text-center" style="background: rgb(0, 102, 177)">
                                <div class="recent-work-inner">
                                    <h3>
                                        <%= link_to project.name, project_path(code: project.team.event.code, project_name: project.path)%>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div><!--/.portfolio-item-->
        <%end%>
                         </div>
        </div>
  </section><!--/#portfolio-item-->

 <div class="container">
  <div class="row">
    <div class="text-center"> <%= will_paginate @projects, renderer: BootstrapPagination::Rails, previous_label: "Voltar", next_label: "Próxima" %> </div>
  </div>
  </div>


</div>

app/views/events/show.html.erb
<% if @event.published %>
<div class="container">
<div class="row text-center">
   <br>
   <h2><%=@event.code %> - <b> <%= @event.name %></b> </h2>
   <hr>
</div>

<div class="col-lg-10 col-lg-offset-1 centered">

    <% if !@event.image.nil? %>
      <%= image_tag @event.image.image.slider.url, height: "200", class:"img-thumbnail" %>
    <% else %>
      <%= image_tag 'bg3.jpg', height: "200", class:"img-thumbnail" %>
    <% end %>
</div>

<div class="col-lg-5 col-lg-offset-1">
  <br>
  <h4>Detalhes do Evento</h4>
  <p><%= @event.description %></p>
  <p><b>Inscrições liberadas:</b>
    <% if @event.release_sign_up %>
      <i class="fa fa-check" style="color: green"></i>
    <% else %>
      <i class="fa fa-times" style="color: red"></i>
    <% end %>
  </p>

       <br>
    <% if @event.release_sign_up %>
    <p class="text-center">
      <%= link_to 'Inscreva-se', event_subscribe_admin_event_path,  class: "btn btn-success btn-lg" %>
    </p>
    <%end%>
</div>

<div class="col-lg-4 col-lg-offset-1">
  <br>
  <p><b>Data:</b> <%= @event.date %></p>
  <p><b>Local:</b> <%= @event.address %></p>

  <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@event.latitude}%2C#{@event.longitude}",  height: "200" %>
</div>
</div>

<div class="container">
<div class="row text-center">
   <h2><br><br>  Projetos MedHacker</h2>
   <hr>
</div>

  <section id="portfolio">
       <div class="row">
				<% @projects.each do |project| %>
                <div class="portfolio-items">
                    <div class="portfolio-item apps col-xs-12 col-sm-4 col-md-4">
                        <div class="recent-work-wrap">

                           <%= image_tag project.images[1].image.project.url , class: "img-responsive" %>

                            <div class="overlay text-center" style="background: rgb(0, 102, 177)">
                                <div class="recent-work-inner">
                                    <h3>
                                        <%= link_to project.name, project_path(code: @event, project_name: project.path)%>
                                    </h3>
                                </div>
                            </div>
                        </div>
                    </div><!--/.portfolio-item-->

          <%end%>
          </div>
          </div>
  </section><!--/#portfolio-item-->
</div>
<%else%>
<div class="container">
  <div class="row text-center">
     <br>
     <h2>Este evento não foi publicado</b> </h2>
     <hr>
  </div>
</div>
<%end%>