config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'events', to: 'events#index'

  get 'events/:code', to: 'events#show', :as => 'event'

  get 'projects', to: 'events#projects', :as => 'events_projects'

  get 'events/:code/:project_name', to: 'project#index', :as => 'project'


  namespace :admin do
    root to: 'events#index'

    resources :users do
      member do
        get 'edit_password', to: 'users#edit_password'
        get 'equipes', to: 'users#equipes'
        patch 'user_password', to: 'users#update_password'
        put 'user_password', to: 'users#update_password'
      end
    end


    get 'home_configuration', to: 'home_configuration#index'

    patch 'home_configuration', to: 'home_configuration#update'
    put 'home_configuration', to: 'home_configuration#update'

    resources :events, param: :code do
      member do
        get 'event_subscribe', to: 'events#event_subscribe'

        resources :event_users, :path => 'users', except:[:show, :edit, :update] do
          collection do
            get 'new_manager', to: 'event_users#new_manager'
            post 'create_manager', to: 'event_users#create_manager'
          end
        end

        resources :teams, as: :event_teams do
          resources :team_users, :path => 'members', :as => 'users', except:[:index, :show]
          resources :projects, except:[:index, :show]
        end
      end
    end
  end

  devise_for :users
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :team
  belongs_to :event

  has_many :sliders, -> { order 'created_at asc' }, :as => :sliderable, dependent: :destroy

  has_many :images, -> { order 'created_at asc' }, :as => :imageable, dependent: :destroy



  accepts_nested_attributes_for :sliders
  accepts_nested_attributes_for :images

  validates :name, :description, :problem, :solution, :team_description, presence: true
  validates :name, uniqueness: true

  #def event
  #  self.team.event
  #end

  def create_images
    problem_image = self.images.build
    File.open('./public/projects/problem_default.jpg') do |f|
      problem_image.image = f
    end

    solution_image = self.images.build
    File.open('./public/projects/solution_default.jpg') do |f|
      solution_image.image = f
    end

    team_image = self.images.build
    File.open('./public/projects/team_default.png') do |f|
      team_image.image = f
    end
  end

  def create_slides
    slide1 = self.sliders.build
    image1 = slide1.build_image
    File.open('./public/projects/slider_default.jpg') do |f|
      image1.image = f
    end
    slide1.title = "Slider"

    slide2 = self.sliders.build
    image2 = slide2.build_image
    File.open('./public/projects/slider_default.jpg') do |f|
      image2.image = f
    end
    slide2.title = "Slider"

    slide3 = self.sliders.build
    image3 = slide3.build_image
    File.open('./public/projects/slider_default.jpg') do |f|
      image3.image = f
    end
    slide3.title = "Slider"
  end

  def self.image_type index
    type = ""
    if index == 0
      type = "Problem"
    elsif index == 1
      type = "Solution"
    else
      type = "Team"
    end

    type
  end

end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::AdminController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_event
  before_action :set_team
  add_breadcrumb "Eventos", :admin_events_path


  # GET /admin/projects
  # GET /admin/projects.json
  #def index
  #  @projects = Project.where(team: @team)
  #end

  # GET /admin/projects/1
  # GET /admin/projects/1.json
  #def show
  #end

  # GET /admin/projects/new
  def new
    add_breadcrumb "#{@event.code}", :admin_event_path
    add_breadcrumb "Equipes", :admin_event_teams_path
    add_breadcrumb "#{@team.name}", admin_event_team_path(@team, code: @event.code)
    add_breadcrumb "New Project", :new_admin_event_team_project_path

    @project = Project.new(team: @team)

    authorize @project
  end

  # GET /admin/projects/1/edit
  def edit
    authorize @project

    add_breadcrumb "#{@event.code}", :admin_event_path
    add_breadcrumb "Equipes", :admin_event_teams_path
    add_breadcrumb "#{@team.name}", admin_event_team_path(@team, code: @event.code)
    add_breadcrumb "Edit Project", :edit_admin_event_team_project_path

    @project.images.order('image DESC')
  end

  # POST /admin/projects
  # POST /admin/projects.json
  def create
    @project = Project.new(project_params)
    @project.create_images
    @project.create_slides

    @project.team = @team
    @project.path = @project.name.parameterize

    authorize @project

    respond_to do |format|
      if @project.save
        format.html { redirect_to edit_admin_event_team_project_path(@project, :code => @event.code,
          :event_team_id => @team) , notice: 'Projeto foi CRIADO com sucesso.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/projects/1
  # PATCH/PUT /admin/projects/1.json
  def update
    authorize @project

    @project.path = @project.name.parameterize
    respond_to do |format|
      if @project.update_attributes(project_params)
        if @project.update_attributes(path: @project.name.parameterize)
          format.html { redirect_to admin_event_team_path(@team, :code => @event.code),
            notice: 'Projeto foi ATUALIZADO com sucesso.' }
          format.json { render :show, status: :ok, location: @project }
        end
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/projects/1
  # DELETE /admin/projects/1.json
  def destroy
    authorize @project

    @project.destroy
    respond_to do |format|
      format.html { redirect_to admin_event_team_path(@team, :code => @event.code),
        notice: 'Projeto foi EXCLUÍDO com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find_by(code: params[:code].upcase)
    end

    def set_team
      @team = Team.find(params[:event_team_id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:id, :name, :description, :problem, :solution, :team_description,
        :facebook_link, :instagram_link, :youtube_link, :email,
        sliders_attributes: [:id, :title, :link, :description, :is_title_link,
          image_attributes: [:id, :image]], images_attributes: [:id, :image] )
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  layout 'projects'

  def index
    @project = Project.find_by_path(params[:project_name])
    @sliders = @project.sliders
  end
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/views/admin/projects/_form.html.erb
<%= simple_form_for([:admin, @project], url: admin_event_team_projects_path(
    @project, :code => @event.code, :event_team_id => @team)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nome" %>
  </div>

  <div class="form-inputs">
    <%= f.input :description, label: "Descrição do Projeto" %>
  </div>

  <div class="form-inputs">
    <%= f.input :problem , label: "Qual o problema"%>
  </div>

  <div class="form-inputs">
    <%= f.input :solution, label: "Qual a solução" %>
  </div>

  <div class="form-inputs">
    <%= f.input :team_description, label: "Descrição da equipe" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Enviar", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/admin/projects/_form2.html.erb
<%= simple_form_for([:admin, @project], url: admin_event_team_project_path(
    @project, :code => @event.code, :event_team_id => @team)) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, label: "Nome" %>
  </div>

  <div class="form-inputs">
    <div class="form-inputs">
      <%= f.input :description, label: "Descrição do Projeto" %>
    </div>

    <div class="form-inputs">
      <%= f.input :problem , label: "Qual o problema"%>
    </div>

    <div class="form-inputs">
      <%= f.input :solution, label: "Qual a solução" %>
    </div>

    <div class="form-inputs">
      <%= f.input :team_description, label: "Descrição da equipe" %>
    </div>

  <div class="well row col-lg-12">
    <h2>Imagens do Projeto</h2>
    <hr>

  <% imgs = ["Problema", " Solução", "Equipe"] %>

  <% @project.images.each.with_index do |image,index| %>
    <%= f.simple_fields_for :images, image do |i| %>
      <div class="row col-lg-3 col-lg-offset-1">
      <div class="form-inputs centered">
        <h3><%= imgs[index] %></h3>
        <%= i.input :image, as: :image_preview, input_html: {preview_version: :project_thumb}, label: "< 450 x 350 >" %>
      </div>
      </div>
    <% end %>
  <% end %>
  <br>
</div>



<div class="row col-lg-12">
    <h2>Slider da Página</h2>
  <hr>
  <% count = 0 %>
  <%= f.simple_fields_for :sliders do |s| %>
  <% count = count + 1 %>

<div class="row col-lg-12 well">
    <h3>Slider <%= count %> </h3>
    <div class="row col-lg-6 ">
    <div class="form-inputs">
      <%= s.input :title, label: "Título" %>
    </div>

    <div class="form-inputs">
      <%= s.input :link, label: "Link"  %>
    </div>

    <div class="form-inputs">
      <%= s.input :description, label: "Descrição" %>
    </div>
    </div>

    <%= s.simple_fields_for :image do |i| %>
    <div class="row col-lg-5 col-lg-offset-1">
      <br>
      <h4 class="centered">Imagem do slider <%= count %> </h4>
      <br>
      <br>
      <div class="form-inputs centered">
        <%= i.input :image, as: :image_preview, input_html: {preview_version: :slider_thumb}, label: "< 1200 x 480 >"%>
      </div>
      </div>
    <% end %>
</div>
  <% end %>
 </div>


   
  <div class="row col-lg-12">
  <h2>Social Links</h2>
  <hr>
  <div class="form-inputs row col-lg-3 col-lg-offset-1">
    <%= f.input :facebook_link %>
  </div>
  <div class="form-inputs row col-lg-3 col-lg-offset-1">
    <%= f.input :youtube_link %>
  </div>
  <div class="form-inputs row col-lg-3 col-lg-offset-1">
    <%= f.input :instagram_link %>
  </div>
  </div>


  <div class="row col-lg-12">
  <h2>Email de Contato</h2>
  <hr>
  <div class="form-inputs row col-lg-6">
    <%= f.input :email %><br>
  </div>
</div>

  <div class="form-actions">

    <%= f.button :submit, value: "Enviar", class: "btn btn-primary btn-lg btn-block" %>
  </div>
<% end %>

app/views/admin/projects/edit.html.erb
<div class="container">
  <div class="row centered">
      <h2> Editar: <b><%= @project.name %></b> </h2>
      <hr>
   </div>

<div class="row col-lg-10 col-lg-offset-1">
<%= render 'form2' %>
<br>
</div>

</div>

<div class="container">
  <div class="well row centered col-lg-10 col-lg-offset-1"> 

    <div class="btn-group">
      <button type="button" class="btn btn-danger btn-sm dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Excluir <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li><%= link_to 'Excluir do Sistema', admin_event_team_project_path(@project, code: @event.code,
          event_team_id: @team), method: :delete, data: { confirm: 'Tem certeza?' } %></li>
      </ul>
    </div>

     
   </div>
   </div>

app/views/admin/projects/index.html.erb
<div class="container">
  <div class="row centered">
      <h2> <%= link_to new_admin_event_team_project_path do %>
        <i class="fa fa-plus-circle"></i> Projeto
      <% end %>
      </h2>
      <hr>
    <h3>Projeto(os): <b><%= @team.name %> </b></h3>
   </div>
<div class="row col-lg-10 col-lg-offset-1">


<% @projects.each do |project| %>
  <h3> <b> <%= project.name %> </b> </h3>
  <h3> Why </h3>
  <p><%= project.problem %> </p>
  <h3> How </h3>
  <p><%= project.solution %> </p>
  <h3> What </h3>
  <p><%= project.team_description %> </p>

  <%= link_to 'Show', admin_event_team_project_path(project,
            code: @event.code, event_team_id: @team) %> |
  <%= link_to 'Edit', edit_admin_event_team_project_path(project,
            code: @event.code, event_team_id: @team) %> |
  <%= link_to 'Destroy', admin_event_team_project_path(project, code: @event.code,
          event_team_id: @team), method: :delete, data: { confirm: 'Tem certeza?' } %>
<% end %>

</div>

</div>

app/views/admin/projects/new.html.erb
<div class="container">
  <div class="row centered">
      <h2>Novo Projeto: <b><%= @team.name %></b> </h2>
      <hr>
   </div>

  <div class="row col-lg-10 col-lg-offset-1">
    <%= render 'form' %>
  </div>

</div>

app/views/admin/projects/show.html.erb
<div class="container">
  <div class="row centered">
      <h2><%= @project.name %>
      </h2>
      <hr>
   </div>
   </div>

<div class="row col-lg-10 col-lg-offset-1 table-responsive">

<h2> <b> <%= @project.name %> </b> </h2>
<h3> Problema </h3>
<p><%= @project.problem %> </p>
<%= image_tag @project.images[0].image.url, size: "100" if !@project.images[0].nil?  %>

<h3> Solução </h3>
<p><%= @project.solution %> </p>
<%= image_tag @project.images[1].image.url, size: "100" if !@project.images[1].nil? %>

<h3> Team Description </h3>
<p><%= @project.team_description %> </p>
<%= image_tag @project.images[2].image.url, size: "100" if !@project.images[2].nil? %>

<p> <%= link_to "Editar", :action => "edit" %> </p>
</div>
</div>