config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  get 'events', to: 'events#index'

  get 'events/:code', to: 'events#show', :as => 'event'

  get 'projects', to: 'events#projects', :as => 'events_projects'

  get 'events/:code/:project_name', to: 'project#index', :as => 'project'


  namespace :admin do
    root to: 'events#index'

    resources :users do
      member do
        get 'edit_password', to: 'users#edit_password'
        get 'equipes', to: 'users#equipes'
        patch 'user_password', to: 'users#update_password'
        put 'user_password', to: 'users#update_password'
      end
    end


    get 'home_configuration', to: 'home_configuration#index'

    patch 'home_configuration', to: 'home_configuration#update'
    put 'home_configuration', to: 'home_configuration#update'

    resources :events, param: :code do
      member do
        get 'event_subscribe', to: 'events#event_subscribe'

        resources :event_users, :path => 'users', except:[:show, :edit, :update] do
          collection do
            get 'new_manager', to: 'event_users#new_manager'
            post 'create_manager', to: 'event_users#create_manager'
          end
        end

        resources :teams, as: :event_teams do
          resources :team_users, :path => 'members', :as => 'users', except:[:index, :show]
          resources :projects, except:[:index, :show]
        end
      end
    end
  end

  devise_for :users
end

app/views/layouts/_form_back.html.erb
<div class="container"> 
  <div class="row col-lg-11 col-lg-offset-1"> 
	<br>
	<%= link_to :back, class: "btn btn-default-outline btn-lg" do %>
		<i class="fa fa-arrow-circle-o-left"></i> Voltar
	<% end %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
<div class="row centered">
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>

    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>

  <% end %>
<% end %>
</div>
</div>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
 <li>
    <%= link_to (admin_root_path) do %>
      <i class="fa fa-dashboard"></i> Dashboard
    <% end %>
 </li>
  <li><%= link_to 'Sair', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Entrar', new_user_session_path %></li>
  <li><%= link_to 'Registrar', new_user_registration_path %></li>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "Admin - MedHacker" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "MedHacker" %>">
    <%= stylesheet_link_tag 'administrator', media: 'all', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag "favicon.png"%>
    <%= csrf_meta_tags %>
    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

  </head>

  <body>
  <section id="container" >
      <!-- **********************************************************************************************************************************************************
      TOP BAR CONTENT & NOTIFICATIONS
      *********************************************************************************************************************************************************** -->
      <!--header start-->
      <header class="header black-bg">
              <div class="sidebar-toggle-box">
                  <div  id="menu-toggle" class="fa fa-bars tooltips" data-toggle="tooltip" href="#menu-toggle" data-placement="right" title="Toggle Navigation"></div>
              </div>
            <!--logo start-->
            <%=link_to (admin_root_path) , class: "logo" do %>
              <b>MedHacker</b>
            <% end %>
            <!--logo end-->
            <div class="nav notify-row" id="top_menu">
                <!--  notification start -->
                <ul class="nav top-menu">
                    <!-- settings start -->
                    <li class="dropdown">
                        <a data-toggle="dropdown" class="dropdown-toggle" href="#" data-toggle="tooltip" title="Projetos Cadastrados!">
                            <i class="fa fa-heartbeat"></i>
                            <span class="badge bg-theme"><%= Project.count %></span>
                        </a>
                    </li>
                    <!-- settings end -->
                </ul>
                <!--  notification end -->
            </div>
            <div class="top-menu">
              <ul class="nav pull-right top-menu">
                  <li>
                    <%= link_to "Sair", destroy_user_session_path, :method=>'delete', class: 'logout'%>
                  </li>
              </ul>
            </div>
        </header>
      <!--header end-->

    <div id="wrapper">

        <!-- Sidebar -->
                   <div id="sidebar-wrapper" class="user"  style="background:#424a5d">
            <ul class="sidebar-nav">
               <p class="centered"><a>
                <br><br><br><br>
                <%= link_to admin_user_path(current_user) do %>
               <%= image_tag("ui-danro.jpg", class: "img-circle",width:"70" ) %></a></p>
               <%end%>
               <h5 class="centered">
                 <b><%= current_user.name %></b>
                 <br>
                 <span class="label label-warning label-mini"><%= current_user.role %></span>

               </h5>


               <li class="mt">
                  <%= link_to(admin_events_path) do %>
                      <i class="fa fa-th"></i>
                      <span>Eventos</span>
                  <% end %>
               </li>

                <% if policy(current_user).index? %>
                <li class="">
                  <%= link_to(admin_users_path) do %>
                    <i class="fa fa-user-md"></i>
                      <span>Usuários</span>
                  <% end %>
                </li>
                <% end %>

              <% if policy(current_user).index? %>
               <li class="">
                  <%= link_to(admin_home_configuration_path) do %>
                      <i class="fa fa-cogs"></i>
                      <span>Página Inicial</span>
                  <% end %>
               </li>
               <% end %>
               
              <li class="">
                  <%= link_to equipes_admin_user_path(current_user) do %>
                      <i class="fa fa-users"></i>
                      <span>Minhas Equipes</span>
                  <% end %>
               </li>
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">
            <div class="container">
                              <div class="row ">
                              <ol class="breadcrumb">
                                <%= render_breadcrumbs :tag => :li, :separator => "" %>
                              </ol>
                                </div>

                              <div class="row ">
                                <%= render 'layouts/messages' %>
                              </div>

                              <div class="row ">
                                <%= yield %>
                              </div>
                              <div class="row ">
                                <%= render '/layouts/form_back' %>                               
                              </div>
                              
                  <!--main content end-->
                </div>
            </div>
       
        <!-- /#page-content-wrapper -->

        <!--footer start-->
        <footer class="site-footer">
            <div class="text-center">
              <strong>&copy; Copyright 2016 &middot; MedHacker</strong>
               <small> &middot; Desenvolvido por: 
                &middot;<a href="http://craosx.com"target="_blank">CRAOSX.com</a></small>

    
                <a href="#" class="go-top"><i class="fa fa-angle-up"></i>
                </a>
            </div>
        </footer>

         </div>
        <!--footer end-->
   <%= javascript_include_tag 'administrator', 'data-turbolinks-track' => true %>


  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Medhacker" %>">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag "favicon.png"%>
    <%= csrf_meta_tags %>

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <title><%= content_for?(:title) ? yield(:title) : "Medhacker" %></title>
  </head>
<!-- NAVBAR
================================================== -->
  <body style="min-height: auto;">
    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to (root_path), class: "navbar-brand" do %>
            <%= image_tag 'logo2.png', height: 50 %>
          <% end %>

        </div>
        <div id="navbar" class="navbar-collapse collapse">
           <ul class="nav navbar-nav navbar-left">
               <li>
                  <%= link_to (events_path) do %>
                    <i class="fa fa-clone"></i> Eventos
                  <% end %>
               </li>
               <li>
                  <%= link_to (events_projects_path) do %>
                    <i class="fa fa-star"></i> Projetos
                  <% end %>
               </li>
           </ul>

          <ul class="nav navbar-nav navbar-right">


            <%= render 'layouts/nav_links_for_auth' %>


          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <%= render 'layouts/messages' %>
    <%= yield %>




    <!-- FOOTER -->

<footer>
<hr>
<div class="container">
    <p class="pull-right"><a href="#" style="color:#000"><i class="fa fa-sort-asc fa-2x"></i></a></p>
    <br>
    <p class="text-center">&copy; Copyright 2016 &middot; MedHacker &middot; Todos os direitos reservados</p>
    <small><p class="text-center" style="color:#888">Desenvolvido por: <a href="http://craosx.com" style="color:#888" target="_blank">CRAOSX.com</a></p></small>
</div>
<hr>
</footer>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/projects.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Medhacker" %>">

    <%= stylesheet_link_tag 'project', media: 'all', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag "favicon.png"%>
    <%= csrf_meta_tags %>

    <!-- Custom Fonts -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <title><%= content_for?(:title) ? yield(:title) : "Medhacker" %></title>
  </head>
  <body>

      <%= render 'layouts/messages' %>

    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #fff;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>

          <%= link_to (root_path), class: "navbar-brand" do %>
            <%= image_tag 'logo.png', height: 50 %>
          <% end %>


        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-left">
              <li><a><span class="fa fa-heartbeat"></span><%= yield :name %></a></li>
              <li><a><span class="fa fa-group"></span><%= yield :team %></a></li>

            </ul>

          <ul class="nav navbar-nav navbar-right">
              <li><a href="#problema">Problema</a></li>
              <li><a href="#solucao">Solução</a></li>
              <li><a href="#equipe">Equipe</a></li>
              <li><p class="navbar-btn text-center"><%= yield :contato %></p></li>
          </ul>




        </div><!--/.nav-collapse -->
      </div>
    </nav>


   <!-- Carousel
================================================== -->
<%= yield :carousel %>
<!-- /.carousel -->


<!-- Marketing messaging and featurettes
================================================== -->
<!-- Wrap the rest of the page in another container to center all the content. -->

<div class="container marketing">

  <!-- START THE FEATURETTES -->

  <div id="problema" class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Qual o problema?</h2>
      <p class="lead"> <%= yield :problem %> </p>
    </div>
    <div class="col-md-5">
      <%= yield :image_problem %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div id="solucao" class="row featurette">
    <div class="col-md-7 col-md-push-5">
      <h2 class="featurette-heading">Qual a solução?</h2>
      <p class="lead"> <%= yield :solution %></p>
    </div>
    <div class="col-md-5 col-md-pull-7">
      <%= yield :image_solution %>
    </div>
  </div>

  <hr class="featurette-divider">

  <div id="equipe" class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">Quem é a equipe?</h2>
      <p class="lead"> <%= yield :team_description %></p>
    </div>
    <div class="col-md-5">
      <%= yield :image_team %>
    </div>
  </div>

  <hr >

  <!-- /END THE FEATURETTES -->

</div><!-- /.container -->

<!-- FOOTER -->
<div class="container text-center">

    <h3 class="">Conheça mais sobre o nosso projeto</h3>
    <br>
    <%= yield :networks %>

    <br><br>
</div>

<footer>
  <hr>
<div class="container">

    <p class="pull-right"><a href="#" style="color:#000"><i class="fa fa-sort-asc fa-2x"></i></a></p>
    <br>
    <p class="text-center">&copy; Copyright 2016 &middot; MedHacker &middot; Todos os direitos reservados</p>
    <small><p class="text-center" style="color:#888">Desenvolvido por: <a href="http://craosx.com" style="color:#888" target="_blank">CRAOSX.com</a></p></small>
</div>
<hr>
</footer>

    <%= javascript_include_tag 'project', 'data-turbolinks-track' => true %>
  </body>
</html>